[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.21"
openssl = "0.10"
openssl-sys = "0.9"
num-bigint = "0.4"
num-integer = "0.1"
